/* ============================================================
   GarageBids Chile — Mock Data
   ============================================================ */

const CARS = [
  {
    slug: "bmw-m3-e92-v8",
    title: "2009 BMW M3 E92 Coupé",
    year: 2009,
    make: "BMW",
    model: "M3",
    version: "E92 Coupé",
    category: "Deportivo",
    location: "Las Condes, Santiago",
    mileage: 88000,
    transmission: "Manual 6 vel.",
    engine: "V8 4.0L S65B40 414 hp",
    drivetrain: "Tracción Trasera",
    color: "Jerez Black Metallic",
    currentBid: 28500000,
    reserveMet: true,
    bidCount: 23,
    timeLeftHours: 5,
    timeLeftMinutes: 42,
    isHot: true,
    isEditorialPick: true,
    endingSoon: true,
    isSinReserva: false,
    status: "active",
    watchers: 74,
    views: 2841,
    commentCount: 18,
    heroImage: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=85&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&q=80&auto=format",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=900&q=80&auto=format",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?w=900&q=80&auto=format",
      "https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=900&q=80&auto=format",
    ],
    highlights: [
      "Último V8 atmosférico del M3 — 414 hp naturalmente aspirados",
      "Transmisión manual de 6 velocidades, sin compromisos",
      "Un dueño desde 2014",
      "Revisión motor completa 2022 (85.000 km)",
      "Mantenciones en BMW Santiago documentadas",
      "Neumáticos Michelin Pilot Sport 4S (2023)",
      "Diferencial activo M (MDCT) funcional",
    ],
    knownFlaws: [
      "Pequeña raspadura en parachoques trasero derecho (ver foto 7)",
      "Cuero del volante con uso normal en zona 9 y 3",
      "Air bag light on ocasional — conector limpiado, sin códigos activos",
    ],
    whyWeLikeIt: "El E92 M3 con motor V8 S65 es uno de los últimos grandes M de la era analógica. Sin turbo, sin filtros electrónicos que te separen de los 414 caballos. Este ejemplar está en el punto dulce: kilometraje real, dueño cuidadoso y el manual de 6 velocidades que hace que cada salida valga. En 5 años más, este auto será leyenda.",
    quirks: [
      "El V8 S65 hace un sonido a 8.400 rpm que no tiene precio",
      "Arranque frío con los 8 cilindros al unísono es una experiencia",
      "La palanca del manual tiene un recorrido corto y directo, casi quirúrgico",
    ],
    maintenance: [
      { date: "Mar 2024", km: "88.000", title: "Service mayor", detail: "Aceite Motul 10W60, filtros, bujías" },
      { date: "Nov 2022", km: "84.500", title: "Revisión motor completa + ajuste válvulas", detail: "Sin desgaste anormal" },
      { date: "Jun 2021", km: "78.200", title: "Embrague + discos de freno", detail: "Valeo OEM, pastillas EBC" },
      { date: "Ene 2020", km: "71.000", title: "Service menor + fluidos", detail: "Concesionario BMW Santiago" },
    ],
    modifications: [
      "Escape Akrapovic Evolution (titanio) — instalado en 2020",
      "Llantas Style 220M 18\" refaccionadas — originales incluidas",
      "Filtro de aire abierto K&N",
    ],
    equipment: [
      "Pack M", "Asientos deportivos en cuero Merino", "Techo solar",
      "Park Distance Control", "HiFi Harman Kardon", "Faros Xenón adaptivos",
      "Llantas Style 220M 18\"", "Cámara de reversa", "Bluetooth",
    ],
    bidHistory: [
      { bidder: "Driver***84", amount: 28500000, time: "hace 12 min" },
      { bidder: "Peti***23", amount: 27800000, time: "hace 28 min" },
      { bidder: "Turbo***11", amount: 27000000, time: "hace 1h" },
      { bidder: "Driver***84", amount: 26500000, time: "hace 2h" },
      { bidder: "AutoFan***", amount: 25500000, time: "hace 3h" },
    ],
    questions: [
      { user: "Peti***23", q: "¿El motor fue abierto alguna vez?", a: "No. La revisión de 2022 fue endoscópica y de válvulas, sin apertura de block. El motor tiene su sellado original de BMW.", time: "hace 4h" },
      { user: "GoldenKey***", q: "¿Tiene Carfax o informe de Autofact?", a: "Tiene informe Autofact actualizado. Se comparte con el ganador de la subasta. Sin siniestros registrados.", time: "hace 6h" },
      { user: "AutoFan***", q: "¿El escape Akrapovic está homologado?", a: "No homologado. Instalado para uso en pista y rutas. Los escapes originales están disponibles si el ganador los quiere.", time: "hace 8h" },
    ],
    sellerNotes: "Auto comprado en 2014 con 42.000 km. Siempre guardado en cochera techada. Principalmente uso fin de semana. Todos los service en BMW Santiago hasta 2021, luego taller especializado M Works. Vendo porque estoy pasando a un auto para familia pero el M3 no merece estar parado.",
    sellerResponsiveness: "Alta — responde en menos de 2h",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "porsche-911-997-s",
    title: "2007 Porsche 911 Carrera S",
    year: 2007,
    make: "Porsche",
    model: "911",
    version: "997.1 Carrera S",
    category: "Deportivo",
    location: "Providencia, Santiago",
    mileage: 62000,
    transmission: "PDK 7 vel.",
    engine: "Flat-6 3.8L 355 hp",
    drivetrain: "Tracción Trasera",
    color: "GT Silver Metallic",
    currentBid: 42000000,
    reserveMet: true,
    bidCount: 31,
    timeLeftHours: 28,
    timeLeftMinutes: 15,
    isHot: true,
    isEditorialPick: true,
    endingSoon: false,
    isSinReserva: false,
    status: "active",
    watchers: 102,
    views: 4120,
    commentCount: 27,
    heroImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=85&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&q=80&auto=format",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=900&q=80&auto=format",
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=900&q=80&auto=format",
    ],
    highlights: [
      "62.000 km verificados — kilometraje bajo para un 997",
      "Motor Mezger derivado — reconocido por longevidad",
      "Historial de mantenciones en Chile completo desde 2010",
      "Revisión ILS (Intermediate Lever Shaft) realizada a 48.000 km",
      "Libre de accidentes — revisado por Autofact",
      "Neumáticos Pirelli P-Zero (2024)",
    ],
    knownFlaws: [
      "Sellado de parabrisas en esquina superior derecha requiere revisión",
      "Retrovisores con microrayones en vidrio — estéticos",
    ],
    whyWeLikeIt: "El 997.1 Carrera S con motor Mezger es el último Porsche 911 con esa arquitectura histórica. Antes de la electrónica que llegó con el 991, este es el 911 más conectado que puedes tener. 62.000 km en 17 años hablan de alguien que lo cuidó, no que lo escondió.",
    quirks: [
      "El arranque en frío con el flat-6 tiene un carácter inconfundible",
      "La dirección es telepática — sientes el asfalto en las palmas",
      "PDK en modo Sport+ convierte el auto en otra cosa",
    ],
    maintenance: [
      { date: "Ene 2025", km: "62.000", title: "Service anual completo", detail: "Aceite Mobil 1, filtros, frenos revisados" },
      { date: "Sep 2022", km: "54.000", title: "Revisión ILS + embrague PDK", detail: "Taller especializado Porsche CL" },
      { date: "Mar 2020", km: "46.500", title: "Neumáticos + alineación", detail: "Michelin PS4" },
    ],
    modifications: ["Ninguna — completamente original"],
    equipment: [
      "Paquete Sport Chrono", "Asientos deportivos cuero", "PASM activo",
      "Faros Bi-Xenón", "Bose Sound", "GPS integrado",
    ],
    bidHistory: [
      { bidder: "AutoFan***", amount: 42000000, time: "hace 2h" },
      { bidder: "Driver***22", amount: 41000000, time: "hace 4h" },
      { bidder: "Peti***07", amount: 40000000, time: "hace 7h" },
    ],
    questions: [
      { user: "Turbo***", q: "¿Se realizó el ILS fix?", a: "Sí, reemplazado en 2022 a 48.000 km con el kit oficial. Factura disponible.", time: "hace 1 día" },
    ],
    sellerNotes: "Auto importado por mí directamente de Alemania en 2010. Siempre en taller especializado. Vendo por cambio de etapa.",
    sellerResponsiveness: "Muy alta",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "toyota-fj-cruiser",
    title: "2014 Toyota FJ Cruiser",
    year: 2014,
    make: "Toyota",
    model: "FJ Cruiser",
    version: "4.0L V6 AT Trail Teams",
    category: "4x4 Icónico",
    location: "Vitacura, Santiago",
    mileage: 104000,
    transmission: "Automático 5 vel.",
    engine: "V6 4.0L 260 hp",
    drivetrain: "4WD permanente",
    color: "Trail Teams Special Edition Cement",
    currentBid: 22000000,
    reserveMet: false,
    bidCount: 14,
    timeLeftHours: 52,
    timeLeftMinutes: 0,
    isHot: false,
    isEditorialPick: false,
    endingSoon: false,
    isSinReserva: true,
    status: "active",
    watchers: 54,
    views: 1980,
    commentCount: 11,
    heroImage: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=85&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=900&q=80&auto=format",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=900&q=80&auto=format",
    ],
    highlights: [
      "Trail Teams Edition — edición especial, mayor valor de reventa",
      "4WD con reductora y diferencial trasero bloqueado de fábrica",
      "SIN RESERVA — el auto se va al mejor postor",
      "Placa de acero en bajos original",
      "Barra antivuelco interior Ironman (instalación profesional)",
      "Toyota Chile — garantía de repuestos asegurada",
    ],
    knownFlaws: [
      "Rayón en puerta trasera izquierda (ver foto)",
      "Radio original reemplazada por Apple CarPlay aftermarket",
      "Emblema trasero repuesto — el original tenía adherencia mala",
    ],
    whyWeLikeIt: "El FJ Cruiser dejó de producirse en 2014 y su valor sigue subiendo. Este es Trail Teams — la edición más buscada — con el diferencial bloqueado trasero de fábrica que muchos FJ no tienen. El precio de mercado sube cada año mientras los disponibles bajan.",
    quirks: [
      "Las puertas traseras abren al revés — genera conversación en todos lados",
      "La visibilidad trasera es pésima — pero el FJ compensa con carisma",
    ],
    maintenance: [
      { date: "Feb 2025", km: "104.000", title: "Service completo", detail: "Aceite, filtros, revisión diferencial" },
      { date: "Jul 2023", km: "95.000", title: "Correa de distribución + bomba agua", detail: "Toyota Chile" },
    ],
    modifications: [
      "Barra antivuelco Ironman interior",
      "Radio Android con Apple CarPlay",
      "Sunroof eléctrico aftermarket",
    ],
    equipment: ["Trail Teams Edition", "Diferencial trasero bloqueado", "Control de tracción", "Asientos de cuero", "Cámara de reversa"],
    bidHistory: [
      { bidder: "Monta***ñero", amount: 22000000, time: "hace 3h" },
      { bidder: "4x4Chile***", amount: 21500000, time: "hace 6h" },
    ],
    questions: [
      { user: "4x4Chile***", q: "¿Ha tenido alguna salida off-road agresiva?", a: "Sí, varias salidas a Atacama y Ruta de los Jesuitas. Siempre con guía y sin daños. El auto está revisado post-expedición.", time: "hace 2 días" },
    ],
    sellerNotes: "FJ de expedición real. Lo compré nuevo y es el auto que más he disfrutado. Vendo solo porque me cambio a una camioneta con más espacio para la familia.",
    sellerResponsiveness: "Alta",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "subaru-wrx-sti-gd",
    title: "2006 Subaru WRX STI GD",
    year: 2006,
    make: "Subaru",
    model: "WRX STI",
    version: "GD Sedan — STI Pink Badge",
    category: "Deportivo",
    location: "Ñuñoa, Santiago",
    mileage: 132000,
    transmission: "Manual 6 vel.",
    engine: "Flat-4 EJ207 2.0T 280 hp",
    drivetrain: "AWD DCCD",
    color: "WR Blue Mica",
    currentBid: 17500000,
    reserveMet: true,
    bidCount: 19,
    timeLeftHours: 4,
    timeLeftMinutes: 18,
    isHot: true,
    isEditorialPick: false,
    endingSoon: true,
    isSinReserva: false,
    status: "active",
    watchers: 66,
    views: 2340,
    commentCount: 22,
    heroImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&q=85&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=900&q=80&auto=format",
    ],
    highlights: [
      "EJ207 original — no remapeado de fábrica, potencia confiable",
      "DCCD (Driver Controlled Centre Differential) funcional",
      "Frenos Brembo de fábrica — mordedores",
      "Documentación completa desde compra nueva",
      "Sin accidentes registrados",
      "Asientos Recaro laterales OEM",
    ],
    knownFlaws: [
      "Turbo original reemplazado a 90.000 km (VF45 OEM de STI)",
      "Interior con desgaste normal para un auto de uso diario 2006",
      "Climatizador de conducción irregular — funciona en automático",
    ],
    whyWeLikeIt: "El GD STI es el ícono generacional. AWD, Brembo, Recaro, DCCD — la lista que los adolescentes de los 2000 memorizaban. Este ejemplar tiene lo difícil: motor EJ207 original y documentación completa. Cada año los limpios son menos.",
    quirks: ["El sonido del turbo fluttering es el himno de esta generación", "El DCCD en posición manual locked + lluvia = diversión controlada"],
    maintenance: [
      { date: "Dic 2024", km: "132.000", title: "Service completo EJ207", detail: "Aceite Motul 10W50, bujías NGK, distribución" },
      { date: "May 2022", km: "118.000", title: "Reemplazo turbo VF45 OEM", detail: "Taller Motorsport Chile" },
    ],
    modifications: ["Escape catback Invidia Q300", "Intercooler Mishimoto", "Filtro HKS"],
    equipment: ["Asientos Recaro OEM", "Frenos Brembo", "Llantas BBS 17\"", "Spoiler OEM STI"],
    bidHistory: [
      { bidder: "Turbo***11", amount: 17500000, time: "hace 30 min" },
      { bidder: "WRC***Fan", amount: 17000000, time: "hace 45 min" },
      { bidder: "SubaruCL***", amount: 16500000, time: "hace 2h" },
    ],
    questions: [],
    sellerNotes: "Mi primer auto nuevo. Lo he cuidado como oro. Vendo con el corazón para financiar algo más práctico.",
    sellerResponsiveness: "Muy alta — responde en menos de 1h",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "land-rover-defender-110",
    title: "2019 Land Rover Defender 110",
    year: 2019,
    make: "Land Rover",
    model: "Defender",
    version: "110 HSE D240",
    category: "4x4 Icónico",
    location: "Lo Barnechea, Santiago",
    mileage: 58000,
    transmission: "Automático 8 vel. ZF",
    engine: "Diesel 2.0L TD4 240 hp",
    drivetrain: "4WD permanente Terrain Response 2",
    color: "Fuji White",
    currentBid: 55000000,
    reserveMet: false,
    bidCount: 8,
    timeLeftHours: 96,
    timeLeftMinutes: 0,
    isHot: false,
    isEditorialPick: true,
    endingSoon: false,
    isSinReserva: false,
    status: "active",
    watchers: 89,
    views: 3210,
    commentCount: 14,
    heroImage: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=1200&q=85&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=900&q=80&auto=format",
    ],
    highlights: [
      "Defender L663 — la nueva generación, totalmente diferente al clásico",
      "Terrain Response 2 con modos Arena, Fango, Nieve, Roca",
      "Cámara de maniobra 3D con vistas submarinas",
      "Capacidad de vadeo: 900mm",
      "Techo panorámico con tejadillo de lona opcional instalado",
      "Pack Explorer con escaleras y rack de techo LR originales",
    ],
    knownFlaws: [
      "Software versión antigua — actualización pendiente en LR Chile",
      "Pequeño error de pantalla en reinicio en frío",
    ],
    whyWeLikeIt: "El Defender nuevo es lo que debería ser: capaz en el barro y presentable en el boulevard. Este es HSE con Pack Explorer — configuración difícil de conseguir en Chile. El diesel TD4 con ZF 8 velocidades tiene torque real desde 1.500 rpm.",
    quirks: ["El Pivi Pro con Google integrado hace el sistema multimedia menos frustrante que el anterior", "El peso del vehículo se siente en curvas — esto no es un SUV urbano"],
    maintenance: [
      { date: "Mar 2025", km: "58.000", title: "Service anual Land Rover Chile", detail: "Garantía vigente hasta 2026" },
    ],
    modifications: ["Rack de techo Voyager con protección LED", "Deflectores de aire originales LR"],
    equipment: ["Pack Explorer", "Pack ColdClimate", "Asientos cuero Windsor", "Meridian Sound", "HUD"],
    bidHistory: [
      { bidder: "Explor***ador", amount: 55000000, time: "hace 5h" },
    ],
    questions: [],
    sellerNotes: "Comprado en Land Rover Chile. Garantía de fábrica vigente hasta marzo 2026. Todo original excepto rack Voyager.",
    sellerResponsiveness: "Alta",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "mazda-rx7-fd-spirit-r",
    title: "1999 Mazda RX-7 Type R Bathurst",
    year: 1999,
    make: "Mazda",
    model: "RX-7",
    version: "FD3S Type R Bathurst",
    category: "Deportivo",
    location: "Maipú, Santiago",
    mileage: 74000,
    transmission: "Manual 5 vel.",
    engine: "Rotativo 13B-REW Biturbo 255 hp",
    drivetrain: "Tracción Trasera",
    color: "Pure White",
    currentBid: 38000000,
    reserveMet: true,
    bidCount: 27,
    timeLeftHours: 38,
    timeLeftMinutes: 22,
    isHot: true,
    isEditorialPick: true,
    endingSoon: false,
    isSinReserva: false,
    status: "active",
    watchers: 118,
    views: 5640,
    commentCount: 34,
    heroImage: "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=1200&q=85&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=900&q=80&auto=format",
    ],
    highlights: [
      "Type R Bathurst — edición limitada para mercado japonés",
      "Motor rotativo 13B-REW con rebuild profesional a 68.000 km",
      "Apex seals nuevas con garantía de 30.000 km",
      "Suspensión Tein adjustable — track-ready",
      "Radiador del motor reemplazado 2023",
      "Aceite rotativo Mazda original — protocolo respetado",
    ],
    knownFlaws: [
      "Consumo de aceite normal del motor rotativo: 1L cada 3.000 km",
      "Aire acondicionado recargado — funciona pero el compresor tiene ruido",
      "Pintura original con microbubbles en capó — repintado profesional en 2020",
    ],
    whyWeLikeIt: "El FD RX-7 es una obra de arte dinámica. El 13B-REW biturbo sequential con 255 hp en 1.270 kg es una ecuación que pocos autos del mundo igualan. El Bathurst es la edición que pocos tienen. El rebuild está documentado y el motor rota exactamente como debe.",
    quirks: ["Debes hacer el cold start ritual: calentar el motor 5 minutos antes de moverlo", "El peso es tan bajo que sientes cada cambio de pavimento"],
    maintenance: [
      { date: "Nov 2024", km: "74.000", title: "Service rotativo", detail: "Aceite Mazda, filtros, bujías NGK" },
      { date: "Ago 2022", km: "68.000", title: "Rebuild motor completo", detail: "Apex seals, sellos laterales, rulimanes — Taller Rotary Chile" },
    ],
    modifications: ["Suspensión Tein Flex Z adjustable", "Intercooler Samco Sport", "Exahust HKS dual"],
    equipment: ["Asientos Recaro aftermarket", "Volante Momo Heritage", "Frenos EBC Yellowstuff"],
    bidHistory: [
      { bidder: "RotaryFan***", amount: 38000000, time: "hace 1h" },
      { bidder: "FD***Chile", amount: 37000000, time: "hace 3h" },
    ],
    questions: [
      { user: "RotaryFan***", q: "¿Se puede ver el motor en frío antes del cierre?", a: "Sí, coordinamos con el ganador antes de la transferencia.", time: "hace 1 día" },
    ],
    sellerNotes: "Traído de Japón en 2018. El rebuild fue invertido con amor y budget real. No es un RX-7 de andar. Es el de tenerlo bien.",
    sellerResponsiveness: "Muy alta",
    documentationStatus: "Completa + certificado de rebuild",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "mercedes-amg-c63-w204",
    title: "2012 Mercedes-AMG C63 W204",
    year: 2012,
    make: "Mercedes-Benz",
    model: "AMG C63",
    version: "W204 6.2L V8 AMG",
    category: "Premium Usado",
    location: "Las Condes, Santiago",
    mileage: 95000,
    transmission: "Automático 7G-MCT AMG Speedshift",
    engine: "V8 6.2L M156 457 hp",
    drivetrain: "Tracción Trasera",
    color: "Obsidian Black Metallic",
    currentBid: 31000000,
    reserveMet: false,
    bidCount: 11,
    timeLeftHours: 72,
    timeLeftMinutes: 30,
    isHot: false,
    isEditorialPick: false,
    endingSoon: false,
    isSinReserva: true,
    status: "active",
    watchers: 47,
    views: 1870,
    commentCount: 9,
    heroImage: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=85&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=900&q=80&auto=format",
    ],
    highlights: [
      "Motor M156 6.2L — último V8 atmosférico de AMG",
      "457 hp de potencia natural, sin turbo",
      "SIN RESERVA",
      "Pack AMG Performance original",
      "Mantenciones completas en taller especializado",
    ],
    knownFlaws: [
      "Faro derecho con humedad leve — sellado pendiente",
      "Cuero de asiento conductor con uso visible",
    ],
    whyWeLikeIt: "El C63 W204 con M156 es el último AMG de la vieja escuela. Sin turbo, sin modos de conducción que te protejan de ti mismo. 457 caballos naturalmente aspirados y el sonido V8 que AMG abandonó después de esta generación.",
    quirks: ["El exhaust en Sport+ es el sonido más dramático de Mercedes jamás producido", "La caja Speedshift de 7 velocidades en manual es táctil y rápida"],
    maintenance: [
      { date: "Ene 2025", km: "95.000", title: "Service mayor V8", detail: "Aceite Mobil 1 AMG, filtros, spark plugs" },
      { date: "Jun 2022", km: "83.000", title: "Frenos + neumáticos", detail: "Brembo, Michelin PS4S" },
    ],
    modifications: [],
    equipment: ["Pack AMG Performance", "Asientos AMG cuero", "Sistema Bang & Olufsen", "Sunroof panorámico"],
    bidHistory: [
      { bidder: "AMG***Fan", amount: 31000000, time: "hace 8h" },
    ],
    questions: [],
    sellerNotes: "Un dueño previo importador. Yo lo compré en 2018. Siempre taller especializado AMG.",
    sellerResponsiveness: "Alta",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "mitsubishi-lancer-evo-ix",
    title: "2006 Mitsubishi Lancer Evolution IX MR",
    year: 2006,
    make: "Mitsubishi",
    model: "Lancer Evolution IX",
    version: "GSR MR — Último EVO IX",
    category: "Deportivo",
    location: "Pudahuel, Santiago",
    mileage: 118000,
    transmission: "Manual 6 vel. Twin Clutch Sport Shift",
    engine: "4G63T 2.0L Turbo 280 hp",
    drivetrain: "AWD Super AYC",
    color: "Passion Red",
    currentBid: 20500000,
    reserveMet: true,
    bidCount: 16,
    timeLeftHours: 60,
    timeLeftMinutes: 45,
    isHot: false,
    isEditorialPick: false,
    endingSoon: false,
    isSinReserva: false,
    status: "active",
    watchers: 58,
    views: 2180,
    commentCount: 15,
    heroImage: "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=1200&q=85&auto=format",
    gallery: [],
    highlights: [
      "EVO IX MR — el último Evo con 4G63 antes del EX",
      "Super AYC activo y funcional — revisado 2024",
      "4G63T original — no abierto, papeles de la compra nueva",
      "Diferencial trasero mecánico Torsen",
      "Sin modificaciones de motor",
    ],
    knownFlaws: [
      "Interior OEM desgastado — Recaro originales con uso",
      "Pintura en faldones con chips de ruta (fotos completas)",
      "Sistema ACD requiere calibración periódica",
    ],
    whyWeLikeIt: "El 4G63 es el motor más legendario del rally. Este EVO IX MR tiene el último de esa era sin haber sido remapeado. Super AYC funcionando y diferencial trasero Torsen — setup original del WRC. Los 118.000 km son bajos para la durabilidad de este motor.",
    quirks: ["El turbo hace lag real entre 2.000 y 3.500 rpm — luego empuja con fuerza pareja", "El Super AYC tarda 50ms en redistribuir torque — perceptible en curva"],
    maintenance: [
      { date: "Abr 2025", km: "118.000", title: "Distribución + service 4G63", detail: "NGK, ACT, Motul" },
      { date: "Oct 2023", km: "110.000", title: "Revisión Super AYC + diferencial", detail: "Mitsubishi Chile" },
    ],
    modifications: ["Escape Invidia N1 catback (no decatalizado)", "Filtro HKS"],
    equipment: ["Asientos Recaro OEM", "Volante Momo OEM", "Frenos Brembo OEM", "Llantas BBS 17\""],
    bidHistory: [],
    questions: [],
    sellerNotes: "Comprado de segunda mano en 2015 con 76.000 km. Siempre taller Mitsubishi y luego taller especializado.",
    sellerResponsiveness: "Alta",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "alfa-romeo-giulia-qv",
    title: "2018 Alfa Romeo Giulia Quadrifoglio",
    year: 2018,
    make: "Alfa Romeo",
    model: "Giulia",
    version: "Quadrifoglio 510 hp",
    category: "Premium Usado",
    location: "Providencia, Santiago",
    mileage: 42000,
    transmission: "Automático 8 vel. ZF",
    engine: "V6 2.9L Biturbo Ferrari 510 hp",
    drivetrain: "Tracción Trasera",
    color: "Alfa Red",
    currentBid: 49000000,
    reserveMet: false,
    bidCount: 7,
    timeLeftHours: 110,
    timeLeftMinutes: 0,
    isHot: false,
    isEditorialPick: true,
    endingSoon: false,
    isSinReserva: false,
    status: "active",
    watchers: 93,
    views: 3750,
    commentCount: 20,
    heroImage: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=85&auto=format",
    gallery: [],
    highlights: [
      "Motor V6 Ferrari — derivado del Roma y Portofino",
      "510 hp con torque de 600 Nm desde 2.500 rpm",
      "42.000 km — bajo kilometraje",
      "Nürburgring record holder de su segmento al lanzamiento",
      "Frenos carbocerámica opcional OEM",
      "Carbono en capó, techo y difusor",
    ],
    knownFlaws: [
      "Control de calidad Alfa: algunos plásticos interiores con acabado inferior",
      "Sistema de infoentretenimiento con lag — interfaz anticuada",
    ],
    whyWeLikeIt: "La Giulia QV tiene el motor más emocionante de la categoría sedan deportivo. El V6 biturbo derivado de Ferrari tiene carácter genuino. 510 hp, tracción trasera, 1.500 kg. La ecuación que hace que los M3, C63 y RS4 se pongan nerviosos.",
    quirks: ["El modo Race desactiva ESP — solo para conductores que saben lo que hacen", "La direción tiene comunicación que los alemanes de la misma categoría no tienen"],
    maintenance: [
      { date: "Feb 2025", km: "42.000", title: "Service oficial Alfa Romeo Chile", detail: "Garantía vigente" },
    ],
    modifications: [],
    equipment: ["Frenos carbocerámica", "Asientos Sparco cuero", "Carbono exterior", "Harman Kardon"],
    bidHistory: [],
    questions: [],
    sellerNotes: "Un dueño. Comprado nuevo en Chile. Toda la garantía de fábrica. Vendo por tema logístico.",
    sellerResponsiveness: "Muy alta",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "volkswagen-golf-gti-mk7",
    title: "2016 Volkswagen Golf GTI Mk7 TCR",
    year: 2016,
    make: "Volkswagen",
    model: "Golf GTI",
    version: "Mk7 Stage 2 TCR Prep",
    category: "Rare Spec",
    location: "Reñaca, Valparaíso",
    mileage: 87000,
    transmission: "DSG 6 vel.",
    engine: "EA888 2.0 TSI Stage 2 — 330 hp",
    drivetrain: "Tracción Delantera",
    color: "Deep Black Pearl Effect",
    currentBid: 16500000,
    reserveMet: false,
    bidCount: 12,
    timeLeftHours: 80,
    timeLeftMinutes: 0,
    isHot: false,
    isEditorialPick: false,
    endingSoon: false,
    isSinReserva: true,
    status: "active",
    watchers: 38,
    views: 1420,
    commentCount: 8,
    heroImage: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&q=85&auto=format",
    gallery: [],
    highlights: [
      "Stage 2 done right — ECU, HPFP, intercooler Forge, turbo IS38",
      "DSG tuneado con Unitronic — respuesta inmediata",
      "SIN RESERVA",
      "Suspensión KW V3 altura regulada",
      "Frenos Tarox con pastillas Ferodo DS",
      "Dyno verificado: 331 hp / 436 Nm",
    ],
    knownFlaws: [
      "Embrague DSG con desgaste acelerado por Stage 2 — revisión recomendada a 95k",
      "Llantas Rotiforma con pequeño impacto en llanta trasera izq",
    ],
    whyWeLikeIt: "El GTI Mk7 bien preparado es una de las mejores relaciones diversión/precio del mercado. Este tiene la preparación correcta: partes conocidas, bien ejecutadas, dino real. 330 hp con DSG en un auto de 1.300 kg es muy rápido en el mundo real.",
    quirks: ["El torque steer en Stage 2 aparece — hay que tenerle respeto", "Launch control en DSG hace el auto un poco bestia"],
    maintenance: [
      { date: "Nov 2024", km: "87.000", title: "Service EA888 Stage 2", detail: "Aceite Liqui-Moly, spark plugs upgraded" },
    ],
    modifications: ["ECU Unitronic Stage 2", "Turbo IS38", "HPFP Forge", "Intercooler Forge", "Suspensión KW V3", "Frenos Tarox"],
    equipment: ["Llantas Rotiforma 18\"", "Asientos cuero/alcantara combo", "Sistema Dynaudio"],
    bidHistory: [],
    questions: [],
    sellerNotes: "Preparación hecha en Alemania mientras vivía allá. Todo con factura. Volví a Chile y no tengo dónde hacerle justicia.",
    sellerResponsiveness: "Alta",
    documentationStatus: "Completa + Dyno sheet",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "jeep-wrangler-rubicon-jk",
    title: "2015 Jeep Wrangler Rubicon JK",
    year: 2015,
    make: "Jeep",
    model: "Wrangler",
    version: "Rubicon Unlimited JK 4 puertas",
    category: "4x4 Icónico",
    location: "Temuco, La Araucanía",
    mileage: 142000,
    transmission: "Manual 6 vel.",
    engine: "3.6L Pentastar V6 285 hp",
    drivetrain: "4WD Dana 44 + Dana 44",
    color: "Granite Crystal Metallic",
    currentBid: 24000000,
    reserveMet: false,
    bidCount: 9,
    timeLeftHours: 120,
    timeLeftMinutes: 0,
    isHot: false,
    isEditorialPick: false,
    endingSoon: false,
    isSinReserva: true,
    status: "active",
    watchers: 44,
    views: 1650,
    commentCount: 6,
    heroImage: "https://images.unsplash.com/photo-1551830820-330a71b99659?w=1200&q=85&auto=format",
    gallery: [],
    highlights: [
      "Rubicon de fábrica — diferenciales Dana 44 delantero y trasero",
      "Bloqueos de diferencial electrónicos delantero y trasero",
      "Sway bar disconnect eléctrico",
      "Lift 2 pulgadas Old Man Emu",
      "SIN RESERVA",
      "Sin daños estructurales — revisado en Jeep Chile",
    ],
    knownFlaws: [
      "Capota de tela con pequeñas roturas en costuras — funcional",
      "Paragolpes trasero aftermarket — original perdido en expedición",
      "Ruido en cardán — inspeccionado, no estructural",
    ],
    whyWeLikeIt: "El Rubicon es la versión que Jeep construye para quienes realmente salen al barro. Dana 44 en ambos ejes, bloqueos electrónicos, sway bar disconnect — viene preparado de fábrica para terreno que otros no se atreven. El lift Old Man Emu es el correcto para este setup.",
    quirks: ["A 140 km/h en autopista el ruido de viento es el precio de las lunas planas", "El clutch manual del JK tiene un punto de enganche único — tarda 2 días en aprenderlo"],
    maintenance: [
      { date: "Ene 2025", km: "142.000", title: "Service Pentastar + diferenciales", detail: "Jeep Chile Temuco" },
      { date: "Mar 2023", km: "128.000", title: "Distribución + bomba agua", detail: "Distribuidor oficial" },
    ],
    modifications: ["Lift 2\" Old Man Emu", "Neumáticos BFG KO2 32\"", "Paragolpes delantero Smittybilt con winch Warn"],
    equipment: ["Bloqueos eléctricos delantero/trasero", "Sway bar disconnect", "Tow hooks OEM", "Rock Rails"],
    bidHistory: [],
    questions: [],
    sellerNotes: "Comprado para expediciones en el sur. Sale de todo. Vendo porque me cambio a Gladiator.",
    sellerResponsiveness: "Normal — vivo en zona rural",
    documentationStatus: "Completa",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },

  {
    slug: "ford-mustang-fastback-1968",
    title: "1968 Ford Mustang Fastback 2+2",
    year: 1968,
    make: "Ford",
    model: "Mustang",
    version: "Fastback 2+2 — Código J 302 V8",
    category: "Clásico Moderno",
    location: "La Reina, Santiago",
    mileage: 94000,
    transmission: "Manual 4 vel. Toploader",
    engine: "V8 302 ci 4.9L 230 hp (restaurado)",
    drivetrain: "Tracción Trasera",
    color: "Highland Green Metallic",
    currentBid: 47000000,
    reserveMet: false,
    bidCount: 22,
    timeLeftHours: 44,
    timeLeftMinutes: 30,
    isHot: true,
    isEditorialPick: true,
    endingSoon: false,
    isSinReserva: false,
    status: "active",
    watchers: 130,
    views: 6870,
    commentCount: 41,
    heroImage: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=85&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=900&q=80&auto=format",
    ],
    highlights: [
      "Fastback 2+2 — la silueta más buscada del Mustang clásico",
      "V8 302 original restaurado y funcional",
      "Toploader 4 velocidades — la caja manual mítica",
      "Pintura Highland Green — color Bullitt",
      "Números matching — VIN verificado",
      "Interior restaurado con materiales originales Ford",
    ],
    knownFlaws: [
      "Sistema eléctrico modernizado — no original (positivo para confiabilidad)",
      "Frenos delanteros convertidos a disco — mejora técnica",
      "AC no instalado — era sin opción en este código",
    ],
    whyWeLikeIt: "El Fastback 1968 en Highland Green es una pregunta retórica. Es la silueta que definió el muscle car. Este tiene los números matching, el Toploader original y la restauración correcta: fiel al original donde importa, modernizado donde ayuda. Un auto de película que se puede usar.",
    quirks: ["El Toploader 4 velocidades tiene el recorrido más largo que conocerás", "El V8 302 en frío tiene una voz que se escucha en toda la cuadra"],
    maintenance: [
      { date: "2023", km: "94.000", title: "Restauración completa", detail: "Pintura, motor, interiores — taller Classic Cars CL, 3 años de trabajo" },
    ],
    modifications: ["Frenos delanteros a disco (mejora)","Sistema eléctrico modernizado (mejora)"],
    equipment: ["Interior buckets OEM restaurado", "Velocímetro Smith clásico", "Radio AM período correcto"],
    bidHistory: [
      { bidder: "Clasico***CL", amount: 47000000, time: "hace 3h" },
      { bidder: "Mustang***1968", amount: 46000000, time: "hace 6h" },
      { bidder: "GarageKing***", amount: 44000000, time: "hace 12h" },
    ],
    questions: [
      { user: "Mustang***1968", q: "¿Tiene el Marti Report?", a: "Sí, Marti Report completo disponible. Números matching confirmados por tercero independiente.", time: "hace 2 días" },
    ],
    sellerNotes: "Restauración de 3 años. No hay atajos en este auto. Cada peso está en el auto. Vendo porque mi señora tiene razón: con 3 hijos el Fastback perdió practicidad.",
    sellerResponsiveness: "Alta",
    documentationStatus: "Completa + Marti Report",
    feeEstimate: { rate: 0.03, min: 150000, max: 1500000 },
  },
];

/* ── Sold cars (vendidos) ───────────────────────────────── */
const SOLD_CARS = [
  {
    title: "2004 Honda S2000 AP2",
    soldPrice: 21500000,
    bidCount: 31,
    watchers: 88,
    daysListed: 7,
    image: "https://images.unsplash.com/photo-1588358524558-b2b4af9b5cf2?w=600&q=80&auto=format",
    editorialComment: "El AP2 en Chile es escaso. Este se fue con 31 pujas en 7 días. El mercado habló.",
    category: "Deportivo",
  },
  {
    title: "2011 Subaru Forester XT Turbo",
    soldPrice: 14900000,
    bidCount: 18,
    watchers: 52,
    daysListed: 7,
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&q=80&auto=format",
    editorialComment: "El XT turbo con caja manual es imposible de encontrar. Se vendió en 48h de reserva alcanzada.",
    category: "4x4 Icónico",
  },
  {
    title: "2017 Mercedes-Benz GLE 63 AMG",
    soldPrice: 62000000,
    bidCount: 9,
    watchers: 97,
    daysListed: 7,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&q=80&auto=format",
    editorialComment: "La subasta más silenciosa y la más alta. 9 pujas, precio final muy por encima de la reserva.",
    category: "Premium Usado",
  },
  {
    title: "1995 Toyota Supra Mk4 NA",
    soldPrice: 33000000,
    bidCount: 44,
    watchers: 210,
    daysListed: 7,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80&auto=format",
    editorialComment: "El Supra NA más visto de nuestra plataforma. 210 watchers, 44 pujas. Comunidad hablando por semanas.",
    category: "Clásico Moderno",
  },
];

/* ── Editorial articles ─────────────────────────────────── */
const ARTICLES = [
  {
    slug: "por-que-los-autos-especiales-merecen-mejor",
    tag: "Opinión",
    title: "Por qué un auto especial no debería venderse como un auto normal",
    lead: "Publicar un M3 en Chileautos al lado de un Sail 2019 no tiene ningún sentido. La información, el proceso y el comprador son completamente distintos.",
    author: "Equipo GarageBids",
    date: "12 mayo 2025",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=900&q=80&auto=format",
  },
  {
    slug: "guia-comprar-primer-auto-deportivo-chile",
    tag: "Guía",
    title: "Guía para comprar tu primer auto deportivo en Chile sin arrepentirte",
    lead: "Presupuesto, mantención, seguros, repuestos. Lo que nadie te dice antes de comprar un auto que te emociona.",
    author: "Equipo GarageBids",
    date: "5 mayo 2025",
    readTime: "8 min",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&q=80&auto=format",
  },
  {
    slug: "clasicos-modernos-que-van-a-subir-de-valor-chile",
    tag: "Editorial",
    title: "Los 7 autos que van a seguir subiendo de precio en Chile",
    lead: "Del FJ Cruiser al RX-7, hay autos que el mercado chileno todavía no termina de valorar. Por ahora.",
    author: "Equipo GarageBids",
    date: "28 abril 2025",
    readTime: "6 min",
    image: "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=900&q=80&auto=format",
  },
];

/* ── Categories ─────────────────────────────────────────── */
const CATEGORIES = [
  { name: "Deportivos", desc: "Autos enfocados en performance. Manual, tracción trasera, historia de circuito bienvenida.", count: 5 },
  { name: "4x4 Icónicos", desc: "FJ, Defender, Wrangler, G-Class. Capacidad real, no SUV urbano disfrazado.", count: 3 },
  { name: "Clásicos Modernos", desc: "Autos de los 80s, 90s y 2000s que ya son historia. Antes de que el precio suba más.", count: 2 },
  { name: "Premium Usado", desc: "BMW, Mercedes, Porsche, Alfa. Con historia documentada y sin el precio de concesionaria.", count: 2 },
  { name: "Modificados Bien Hechos", desc: "Stage 2, suspensión, audio. Preparaciones con factura y propósito real.", count: 1 },
  { name: "Rare Specs", desc: "Versiones de edición limitada, colores especiales o configuraciones únicas en Chile.", count: 1 },
];

/* ── Helpers ────────────────────────────────────────────── */
function formatCLP(n) {
  return "$" + n.toLocaleString("es-CL");
}

function getTimeLabel(hours, minutes) {
  if (hours < 1) return `${minutes}m restantes`;
  if (hours < 24) return `${hours}h ${minutes}m`;
  const days = Math.floor(hours / 24);
  const remH = hours % 24;
  return `${days}d ${remH}h`;
}

function isUrgent(hours) {
  return hours < 12;
}

function calcFee(bid, rate, min, max) {
  const fee = Math.max(min, Math.min(max, Math.round(bid * rate)));
  return { fee, total: bid + fee };
}
